<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PagoDirecto.Infrastructure</RootNamespace>
    <PackageId>PagoDirecto.Infrastructure</PackageId>
    <Product>PagoDirecto.Infrastructure</Product>
    <Description>Capa de Infraestructura para PagoDirectoApi (EF Core, Repositorios e Integraciones)</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PagoDirecto.Application\PagoDirecto.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Confluent.Kafka" Version="2.14.2" />
    <PackageReference Include="itext" Version="9.6.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="OpenIddict.AspNetCore" Version="7.5.0" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.5.0" />
  </ItemGroup>

</Project>

