<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Furaqui.Domain</RootNamespace>
    <PackageId>Furaqui.Domain</PackageId>
    <Product>Furaqui.Domain</Product>
    <Description>Capa de Dominio para FuraquiApi (Modelos, Entidades, Enums)</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

</Project>
